version: "3"

tasks:
  build:
    desc: "Build the project"
    cmds:
      - GOFLAGS=-mod=mod go build -o bin/done main.go

  run:
    desc: "Run the project"
    cmds:
      - GOFLAGS=-mod=mod go run main.go
